version: '3.6'
services:
  fuseki:
    image: localhost/aggie-experts/harvest-grant:HEAD
    ports:
      - "3030:3030"
    environment:
      LOCAL_USER_ID=1001
    tmpfs:
      - /tmp
    command: server
    volumes:
      -/home/quinn/aggie-test:/home/ucd.process
      mybucket:
        name: ucd-research-profiles/vrt
        driver: ofekmeister/gcsfs
        driver_opts:
          key: ${SERVICE_KEY}
#    workdir:
#      /home/ucd.process/workdir
#      - type: tmpfs
#        target: /var/lib/fuseki/databases/harvest
#        tmpfs:
#          size: 1000000000
#      - ./iam.hdt:/var/lib/fuseki/hdt/iam.hdt

#network:
#  default:
#    name:ae-harvest
