
services:

  harvest:
    image: ${HARVEST_IMAGE:-localhost/local-dev/harvest:sandbox}
    env_file:
      - .env
    environment:
      - EXPERTS_CACHE_ROOT_DIR=/opt/cache
      - GOOGLE_APPLICATION_CREDENTIALS=/service-account.json
    volumes:
      - ./harvest/lib:/opt/harvest/lib
      - ./harvest/bin:/opt/harvest/bin
      - ./harvest/vocabularies:/opt/harvest/vocabularies
      - ./dagster/defs.py:/opt/harvest/defs.py
      - data_cache:/opt/cache
      - dagster_home:/opt/dagster/dagster_home
      - ./service-account.json:/service-account.json
    ports:
      - "3000:3000"
    command: bash -c "dagster dev -f /opt/harvest/defs.py -h 0.0.0.0"

  elasticsearch:
    image: ${ES_IMAGE:-localhost/local-dev/fin-elastic-search:sandbox}
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: unless-stopped

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:16}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  superset:
    # image: ${SUPERSET_IMAGE}
    image: apache/superset:latest
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key
      - SUPERSET_DATABASE_URI=postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - superset_home:/app/superset_home
      - superset_init:/etc/superset/init
    # command: ["bash", "-c", "/app/docker/superset-start.sh"]

volumes:
  data_cache:
    driver: local
  dagster_home:
    driver: local
  es-data:
    driver: local
  pg_data:
    driver: local
  superset_home:
    driver: local
  superset_init:
    driver: local