version: '3'

services:
  # Fuseki is used to harvest data, and as a check on data as well
  fuseki:
    image: &IMG ${ORG}/harvest:${TAG}
    volumes:
      - &SERVICE_ACCOUNT ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-./service-account.json}:/etc/fin/service-account.json
      - fuseki-data:/home/ucd.process
    ports:
      - ${DB_PORT:-3030}:3030
    environment:
      - JVM_ARGS=${JVM_ARGS:- -Xmx16g}
    restart: unless-stopped
    command:
      HDT=import server
    # command: bash -c 'tail -f /dev/null'

###
# Docker data volumes
###
volumes:
  fuseki-data:
    driver: local
