PREFIX : <http://oapolicy.universityofcalifornia.edu/vocab#>
PREFIX expert: <http://experts.ucdavis.edu/expert/>
PREFIX oap: <http://oapolicy.universityofcalifornia.edu/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX ucdlib: <http://schema.library.ucdavis.edu/schema#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
select distinct (?username as ?USERNAME__) ?EXPERT__ ?filename where {
  graph oap: {
    [] :username ?username;
       :is-public "true";
       .
  }
  graph <http://iam.ucdavis.edu/> {
    ?expert a ucdlib:Expert;
            ucdlib:eduroam ?username;
            ucdlib:is-visible true;
            .
    bind(concat("expert/",?EXPERTID__,".jsonld.json") as ?filename)
    bind(uri(concat("http://experts.ucdavis.edu/expert/",?EXPERTID__)) as ?EXPERT__)
  }
}
