PREFIX : <http://oapolicy.universityofcalifornia.edu/vocab#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX cdl: <ark:/87287/d7_cdltest_/>
PREFIX expert: <http://experts.ucdavis.edu/expert/>
PREFIX experts: <http://experts.ucdavis.edu/>
PREFIX oap: <http://oapolicy.universityofcalifornia.edu/>
PREFIX ucdlib: <http://schema.library.ucdavis.edu/schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

select distinct (?username as ?USERNAME__) ?EXPERT__ (?relationship as ?RELATIONSHIP__) ?filename where {
  graph oap: {
    ?relationship :type ?type;
                  :related ?grant;
                  :related ?user;
                  .
    ?grant :category "grant";
         .
    ?user :category "user";
          :username ?username;
          :is-public "true";
          .
  }
  graph <http://iam.ucdavis.edu/> {
    ?expert a ucdlib:Expert;
         ucdlib:is-visible true;
         ucdlib:eduroam ?username;
         .
  }
  filter(regex(?username,"@ucdavis.edu"))
  bind(uri(concat("http://experts.ucdavis.edu/expert/",?EXPERTID__)) as ?EXPERT__)
  bind(replace(str(?relationship),str(oap:),"ark:/87287/d7mh2m/relationship/") as ?id)
  bind(concat('expert/',?EXPERTID__,"/",?id,".jsonld.json") as ?filename)
}
