openapi: 3.0.0
info:
  title: Aggie Experts API
  version: 1.0.0
  description: This is the Swagger documentation for Aggie Experts.
  license:
    name: Licensed Under MIT
    url: https://spdx.org/licenses/MIT.html
  contact:
    name: Online Strategy - UC Davis Library
    url: https://library.ucdavis.edu/online-strategy/
components:
  schemas: {}
paths:
