PREFIX experts: <http://experts.ucdavis.edu/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ucdrp: <http://experts.ucdavis.edu/schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
	?fin_coa_code
    a ucdrp:ChartOfAccounts;
	  rdfs:label ?fin_coa_desc;
}
WHERE {
  BIND(URI(CONCAT(str(ucdrp:), "ChartOfAccounts_", ?fin_coa_cd)) as ?fin_coa_code)
}
