PREFIX experts: <http://experts.ucdavis.edu/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX ucdrp: <http://experts.ucdavis.edu/schema#>

CONSTRUCT {
	?fis_org a foaf:Organization,vivo:Department;
          rdfs:label ?home_dept_nm;
          vivo:abbreviation ?home_dept_abrv_nm;
          ucdrp:campus ?campus_cd;
          ucdrp:division ?division_cd;
          .

}
#FROM
#	<file:grants.csv>
WHERE {
	BIND(URI(CONCAT(str(experts:), "fis/org/", ?campus_cd,"/",?home_dept_cd)) as ?fis_org)
}
