PREFIX kfs: <ark:/87287/d7gt0q/>
PREFIX : <ark:/87287/d7gt0q/schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
	?fin_coa_code
    a :ChartOfAccounts;
	  rdfs:label ?fin_coa_desc;
}
WHERE {
  BIND(URI(CONCAT(str(:), "ChartOfAccounts_", ?fin_coa_cd)) as ?fin_coa_code)
}
