#! /usr/bin/make

hdt:=authoritiesgenreForms.hdt  vocabularygraphicMaterials.hdt

rdf2hdt:='~/hdt-java/hdt-java-package/target/hdt-java-package-2.1-SNAPSHOT-distribution/hdt-java-package-2.1-SNAPSHOT/bin/rdf2hdt.sh'
