openapi: 3.0.3
info:
  title: SiteFarm API
  description: |-
   The SiteFarm API returns an array of expert profiles matching a provided list of IDs. This allows external systems including UCD SIteFarm to integrate Aggie Experts data into their sites.
   Publically available API endpoints can be used for access to experts data.

   Some elevated users can use this
  termsOfService: http://swagger.io/terms/
  contact:
    email: aggie-experts@ucdavis.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: ${VERSION}
servers:
  - url: ${HOST}/sitefarm
tags:
  - name: SiteFarm
    description: SiteFarm Information
paths:
  /api/{experts}:
    get:
      tags:
        - experts
      summary: Find experts match a list id IDs
      description: Returns an array of expert profiles
      operationId: getExpertsByIds
      parameters:
        - name: experts
          in: path
          description: A comma separated list of expert IDs
          example: experts/66356b7eec24c51f01e757af2b27ebb8
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid ID supplied
        '404':
          description: Expert not found
      security:
        - oauth2: []
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://sandbox.auth.library.ucdavis.edu/realms/aggie-experts/protocol/openid-connect/auth
          scopes:
            viewer: view your account
            owner: modify your account
            admin: Administrative login
