steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "bash"
    args: [ '-c', 'docker pull ${_ORG}/${_IMAGE}:latest || true' ]
    env:
      - 'REPO_NAME=$REPO_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'REF_NAME=$REF_NAME'
      - '_UCD_LIB_INITIATOR=$_UCD_LIB_INITIATOR'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "bash"
    args: [ '-c', 'docker build --build-arg ORG=${_ORG} --build-arg REF_NAME=${REF_NAME} --cache-from ${_ORG}/${_IMAGE}:latest -t ${_ORG}/${_IMAGE}:$REF_NAME .' ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "bash"
    args: [ '-c', 'docker tag ${_ORG}/${_IMAGE}:$REF_NAME ${_ORG}/${_IMAGE}:latest' ]

images: ['${_ORG}/${_IMAGE}:$REF_NAME', '${_ORG}/${_IMAGE}:latest']

substitutions:
  _ORG: gcr.io/ucdlib-pubreg
