prefix : <http://oapolicy.universityofcalifornia.edu/vocab#>
prefix expert: <http://experts.ucdavis.edu/expert/>
PREFIX oap: <http://oapolicy.universityofcalifornia.edu/>
PREFIX ucdlib: <http://schema.library.ucdavis.edu/schema#>
select distinct (?username as ?USERNAME__) ?filename where {
  graph oap: {
    [] :username ?username;
       :is-public "true";
       .
    bind(md5(?username) as ?id)
    bind(concat("expert/",?id,".jsonld.json") as ?filename)
  }
}
