# Query for grants
PREFIX : <ark:/87287/d7gt0q/schema#>
# PREFIX ae: <ark:/87287/d7c08j/>
PREFIX iam: <http://iam.ucdavis.edu/>
PREFIX experts: <http://experts.ucdavis.edu/>
PREFIX grant: <ark:/87287/d7gt0q/grant/>
PREFIX kfs: <ark:/87287/d7gt0q/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ucdlib: <http://schema.library.ucdavis.edu/schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdl: <http://oapolicy.universityofcalifornia.edu/>
select distinct
(?grant AS ?id)
("grant" AS ?category)
("c-davis" AS ?type)
("" AS ?url)
(?grant as ?institution_reference)
?flowThruFunding
?title
?pi
?funding_type
?start_date
?end_date
?ucop_sponsor
?funder_name
?funder_reference
?amount_value
("USD" AS ?amount_currency_code)
("TRUE" AS ?visible)
where {
  GRAPH <ark:/87287/d7c08j/> {
    ?grant a vivo:Grant,?grant_class ;
              rdfs:label ?title;
              # ucdlib:piName ?pi;
              vivo:totalAwardAmount ?amount_value;
              vivo:dateTimeInterval [
                                      vivo:start/vivo:dateTime ?start_date;
                                      vivo:end/vivo:dateTime ?end_date;
                                    ];
    .

    # VALUES (?funding_type ?grant_class) {
    #   ("Instruction" :GrantTypeInstruction)
    #   ("Research" :GrantTypeResearch)
    #   ("Service /Other" :GrantTypeService)
    #   ("Academic Support" :GrantTypeAcademicSupport)
    #   ("Student Services" :GrantTypeStudentService)
    #   ("Scholarships / Fellowships" :GrantTypeScholarship)
    #   ("Research" :GrantTypeDefault)
    # }

    # OPTIONAL {
    #   ?grant ucdlib:flowThruFunding ?flowThruFunding.
    # }

    OPTIONAL {
      ?grant vivo:assignedBy ?ucop_sponsor;
             vivo:sponsorAwardId ?funder_reference;
             .
      ?ucop_sponsor rdfs:label ?funder_name.
    }
    # # This filters grants without a value oracle_award_number
    # filter(! regex(str(?grant),"K-"))
  }
} order by ?id limit 100
