PREFIX cd: <http://citydata.wu.ac.at/ns#>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX uc: <http://ucuenca.edu.ec/ontology#>
PREFIX : <ark:/87287/d7gt0q/schema#>
PREFIX experts: <http://experts.ucdavis.edu/>
PREFIX grant: <ark:/87287/d7gt0q/grant/>
PREFIX kfs: <ark:/87287/d7gt0q/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX person: <http://experts.ucdavis.edu/person/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ucdlib: <http://schema.library.ucdavis.edu/schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX iam: <http://iam.ucdavis.edu/>
PREFIX cdl: <http://oapolicy.universityofcalifornia.edu/>

select ?category_1 ?id_1 ?category_2 ?id_2 ?link_type_id ("TRUE" as ?visible)
  WHERE {
    VALUES (?role ?link_type_id ?e_role) {
#       (:GrantAccountManagerRole "183" "Researcher on" )
       (:GrantOtherRole "138" "Researcher on" )
       (:GrantProjectLeaderRole "118" "Project Lead of")
       (:GrantCoPrincipalInvestigatorRole "121" "Co-PI of")
       (:GrantProgramDirectorRole "137" "Program Director of")
       (:GrantCoreLeaderRole "119" "Co leader on")
       (:GrantKeyPersonnelRole "97" "Senior personal of")
       (:GrantPrincipalInvestigatorRole "120" "Primary investigator for")
     }

    GRAPH kfs: {
        ?grant a vivo:Grant;
               vivo:relates [ a :GrantPrincipalInvestigatorRole;
               obo:RO_0000052 ?pi];
               vivo:relates ?related
               .
   	?related a ?role ;
               obo:RO_0000052 ?expert;
               .

  }

  GRAPH cdl: {
	    ?expert ucdlib:proprietary_id ?ucpath .
    }

  bind("user" as ?category_1)
  bind("grant" as ?category_2)
  bind(?ucpath as ?id_1)
  bind(?grant as ?id_2)
  }

limit 100000

