#! /bin/bash

function main.cmd() {
  declare -g -A G=(
    [dir]="."
    [shell_getopt]=${FLAGS_GETOPT_CMD:-getopt}
    [verbose]=0
    [exe]=$(basename "$0")
    [org]=localhost/aggie-experts
    [cache]=latest
#    [fin_org]=localhost/local-dev
    [fin_org]=gcr.io/ucdlib-pubreg
    [fin_tag]=sandbox
    [noop]=
    )

    local opts;
    if ! opts=$(${G[shell_getopt]} -o nv:d:f: --long fin_tag:,fin_org:,dir:,noop,tag:,help -n "build-fin" -- "$@"); then
    echo "Bad Command Options." >&2 ; exit 1 ; fi

    eval set -- "$opts"

    local defaults=1
    declare -A CMD;
    while true; do
	    case $1 in
        -d | --dir ) CMD[dir]=$2; shift 2;;
	      -v | --tag) CMD[tag]=$2;  shift 2;;
	      -f | --fin_tag) CMD[fin_tag]=$2;  shift 2;;
	      -f | --fin_org) CMD[fin_org]=$2;  shift 2;;
        -n | --noop) CMD[noop]="echo"; shift;;
        -h | --help ) exec pod2text "$0";;
	      -- ) shift; break;;
	      *) shift; break;
      esac
    done

    # command line over global
    for i in "${!CMD[@]}"; do
      [[ -n ${CMD[$i]} ]] && G[$i]=${CMD[$i]};
    done

    # Now G has all values
    build
}

# Fill in G[] with repo defaults
function repo_G () {
  G[repo]=$(basename -s .git $(git config --get remote.origin.url))
#  G[branch_name]=$(git branch --show-current)
#  G[tag_name]=$(git tag --points-at HEAD)
  G[base]=$(git rev-parse --show-toplevel)
  #G[gcloud_user]=$(gcloud auth list --filter="status:ACTIVE"  --format="value(account)")
  G[sha]=$(git log -1 --pretty=%h)
#  G[ref_name]=${G[tag_name]:-${G[branch_name]}}
   G[tag]=${G[tag]:-$(git describe --tags --always --dirty)}
}

function _build_fin() {
  echo "(cd fin; BRANCH_NAME=${G[fin_tag]} LOCAL_DEV=true devops/build.sh)"
  (cd fin; BRANCH_NAME=${G[fin_tag]} LOCAL_DEV=true devops/build.sh) 2>&1 >> ${G[dir]}/build.log
}

function _build_aggie_experts() {
  cd $(dirname "$0")
  repo_G
  cd ${G[base]}

  declare -a services=(init fcrepo base-service)

  for service in "${services[@]}"; do
    local image=${G[org]}/${service}:${G[tag]}
    local fin_base=${G[fin_org]}/fin-base-service:${G[fin_tag]}
    local fin_init=${G[fin_org]}/fin-init:${G[fin_tag]}
    local fin_fcrepo=${G[fin_org]}/fin-fcrepo:${G[fin_tag]}

    ${G[noop]} docker build \
            --build-arg FIN_INIT=$fin_init \
           --build-arg FIN_SERVER_IMAGE=$fin_base \
           --build-arg FIN_FCREPO_BASE_IMAGE=$fin_fcrepo \
           -t $image \
           --cache-from $image \
           services/${service}
  done
  # # Build base differently for some reason

#   local image=${G[org]}/base-service:${G[tag]}#

#   ${G[noop]} docker build \
#              --build-arg FIN_SERVER_IMAGE=$fin_base \
#              -t $image \
#              --cache-from $image \
#              services/fin


}

function build() {
    local opts;
    if ! opts=$(${G[shell_getopt]} -o n --long=all,aggie-experts,fin,no-aggie-experts,no-fin -n "build" -- "$@"); then
    echo "Bad build options." >&2 ; exit 1 ; fi

    eval set -- "$opts"

  cd ${G[dir]}
  repo_G

  declare -A CMD=(
    [aggie-experts]=1
    [fin]=
  );
    while true; do
	    case $1 in
        --all ) CMD[aggie-experts]=1; CMD[fin]=1; shift;;
        --aggie-experts ) CMD[aggie-experts]=1; shift;;
        --no-aggie-experts ) CMD[aggie-experts]=; shift;;
        --fin ) CMD[fin]=1; shift;;
        --no-fin ) CMD[fin]=; shift;;
        -n | --noop) CMD[noop]="echo"; shift;;
	      -- ) shift; break;;
	      *) shift; break;
      esac
    done

    declare -p CMD

    if [[ -n ${CMD[fin]} ]]; then
      _build_fin
    fi

    if [[ -n ${CMD[aggie-experts]} ]]; then
      _build_aggie_experts
    fi

}

main.cmd "$@"
exit 0
