prefix : <http://iam.ucdavis.edu/schema#>
prefix person: <http://experts.ucdavis.edu/person/>
select ?kerb ?filename ?graph  where {
  graph ?g {
    [] :userID ?kerb.
    bind(md5(concat(str(?kerb), "@ucdavis.edu")) as ?id)
    bind(concat("person/",?id,".jsonld.json") as ?filename)
    bind(uri(concat("info:fedora/",?filename)) as ?graph)
  }
}
