#! /usr/bin/env yml-docker-compose.sh
version: '3'
services:
  fuseki:
    image: local-dev/ucdi-jena-fuseki-hdt:${FUSEKI_VERSION:-main}
    volumes:
      - ./configuration:/etc/fuseki/configuration
      - ./hdt:/var/lib/fuseki/hdt
    ports: # still exposed for admin access
      - ${FUSEKI_HOST_PORT:-3030}:3030

volumes:
  fuseki-data:
