PREFIX : <ark:/87287/d7gt0q/schema#>
PREFIX experts: <http://experts.ucdavis.edu/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX grant: <ark:/87287/d7gt0q/grant/>
PREFIX kfs: <ark:/87287/d7gt0q/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX expert: <http://experts.ucdavis.edu/expert/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ucdlib: <http://schema.library.ucdavis.edu/schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
	?fis_org a foaf:Organization,vivo:Department;
          rdfs:label ?home_dept_nm;
          vivo:abbreviation ?home_dept_abrv_nm;
          :campus ?campus_cd;
          :division ?division_cd;
          .

}
#FROM
#	<file:grants.csv>
WHERE {
	BIND(URI(CONCAT(str(kfs:), "org/", ?campus_cd,"/",?home_dept_cd)) as ?fis_org)
}
