prefix : <http://oapolicy.universityofcalifornia.edu/vocab#>
prefix cdl: <ark:/87287/d7_cdltest_/>
prefix experts: <http://experts.ucdavis.edu/>
prefix oap: <http://oapolicy.universityofcalifornia.edu/>
prefix person: <http://experts.ucdavis.edu/person/>
prefix ucdlib: <http://schema.library.ucdavis.edu/schema#>
prefix vivo: <http://vivoweb.org/ontology/core#>

#describe ?pub
select ?pub ?filename ?graph
WHERE {
  graph ?g {
    ?pub :category "publication";
         :is-public "true";
         :ever-approved "true";

  filter (isiri(?pub))
  bind(replace(str(?pub),str(oap:),"") as ?id)
  bind(concat(str(cdl:),"work/",?id,".jsonld.json") as ?filename)
  bind(uri(concat("info:fedora/",?filename)) as ?graph)
  }
}
